import { MealType } from '@prisma/client';

export interface SeedRecipe {
  title: string;
  description: string;
  imageUrl: string;
  instructions: string;
  prepTime: number;
  cookTime: number;
  servings: number;
  categories: MealType[];
  tags: string[];
  ingredients: Array<{ name: string; quantity: number; unit: string }>;
}

export const seedRecipes: SeedRecipe[] = [
  {
    title: 'Tortilla española',
    description: 'La clásica tortilla de patatas, jugosa por dentro y dorada por fuera.',
    imageUrl: 'https://images.unsplash.com/photo-1607116667981-ff71d5032347?w=800',
    instructions: '1. Pelar y cortar las patatas en láminas finas.\n2. Freír las patatas en abundante aceite a fuego medio hasta que estén tiernas (15 min).\n3. Batir los huevos con sal.\n4. Escurrir las patatas y mezclar con el huevo.\n5. En una sartén con poco aceite, verter la mezcla.\n6. Cocinar a fuego medio-bajo 5 minutos.\n7. Dar la vuelta con un plato y cocinar otros 3-4 minutos.',
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    categories: [MealType.COMIDA, MealType.CENA],
    tags: ['Comfort food', 'Económico'],
    ingredients: [
      { name: 'Patatas', quantity: 4, unit: 'unidades' },
      { name: 'Huevos', quantity: 6, unit: 'unidades' },
      { name: 'Aceite de oliva', quantity: 200, unit: 'ml' },
      { name: 'Sal', quantity: 1, unit: 'pizca' },
    ],
  },
  {
    title: 'Gazpacho andaluz',
    description: 'Sopa fría de tomate perfecta para el verano.',
    imageUrl: 'https://images.unsplash.com/photo-1509482560494-4126f8225994?w=800',
    instructions: '1. Lavar y trocear los tomates, el pepino, el pimiento y la cebolla.\n2. Poner todo en la batidora con el ajo, el vinagre, el aceite y la sal.\n3. Triturar hasta obtener una textura fina.\n4. Colar si se desea.\n5. Refrigerar al menos 2 horas antes de servir.',
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    categories: [MealType.COMIDA, MealType.CENA],
    tags: ['Saludable', 'Vegano', 'Rápido', 'Sin gluten'],
    ingredients: [
      { name: 'Tomates maduros', quantity: 1, unit: 'kg' },
      { name: 'Pepino', quantity: 1, unit: 'unidad' },
      { name: 'Pimiento verde', quantity: 1, unit: 'unidad' },
      { name: 'Cebolla', quantity: 0.5, unit: 'unidad' },
      { name: 'Ajo', quantity: 1, unit: 'diente' },
      { name: 'Aceite de oliva', quantity: 50, unit: 'ml' },
      { name: 'Vinagre de Jerez', quantity: 30, unit: 'ml' },
      { name: 'Sal', quantity: 1, unit: 'pizca' },
      { name: 'Agua fría', quantity: 100, unit: 'ml' },
    ],
  },
  {
    title: 'Tostadas con tomate y jamón',
    description: 'El desayuno español por excelencia.',
    imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800',
    instructions: '1. Tostar las rebanadas de pan.\n2. Rallar los tomates o triturarlos.\n3. Untar el tomate sobre las tostadas.\n4. Añadir un chorrito de aceite de oliva y sal.\n5. Colocar las lonchas de jamón encima.',
    prepTime: 5,
    cookTime: 3,
    servings: 2,
    categories: [MealType.DESAYUNO],
    tags: ['Rápido', 'Económico'],
    ingredients: [
      { name: 'Pan de pueblo', quantity: 4, unit: 'rebanadas' },
      { name: 'Tomates maduros', quantity: 2, unit: 'unidades' },
      { name: 'Jamón serrano', quantity: 4, unit: 'lonchas' },
      { name: 'Aceite de oliva virgen extra', quantity: 20, unit: 'ml' },
      { name: 'Sal', quantity: 1, unit: 'pizca' },
    ],
  },
  {
    title: 'Pollo al limón con arroz',
    description: 'Pollo jugoso con una salsa cítrica acompañado de arroz blanco.',
    imageUrl: 'https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=800',
    instructions: '1. Salpimentar los muslos de pollo.\n2. Dorar el pollo en una sartén con aceite por ambos lados (5 min por lado).\n3. Añadir el zumo de limón, el caldo y el ajo.\n4. Tapar y cocinar a fuego medio 20 minutos.\n5. Mientras, cocer el arroz en agua con sal (12 min).\n6. Servir el pollo con la salsa sobre el arroz.',
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    categories: [MealType.COMIDA],
    tags: ['Sin gluten', 'Económico'],
    ingredients: [
      { name: 'Muslos de pollo', quantity: 4, unit: 'unidades' },
      { name: 'Limón', quantity: 2, unit: 'unidades' },
      { name: 'Arroz', quantity: 300, unit: 'g' },
      { name: 'Caldo de pollo', quantity: 200, unit: 'ml' },
      { name: 'Ajo', quantity: 3, unit: 'dientes' },
      { name: 'Aceite de oliva', quantity: 30, unit: 'ml' },
      { name: 'Sal', quantity: 1, unit: 'pizca' },
      { name: 'Pimienta', quantity: 1, unit: 'pizca' },
    ],
  },
  {
    title: 'Ensalada César',
    description: 'Ensalada fresca con pollo crujiente y salsa César casera.',
    imageUrl: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=800',
    instructions: '1. Cortar el pollo en tiras y salpimentar.\n2. Pasar el pollo por la sartén hasta que esté dorado.\n3. Tostar el pan cortado en cubos con un poco de aceite en el horno (180°C, 8 min).\n4. Mezclar para la salsa: mayonesa, zumo de limón, ajo rallado, queso parmesano y agua.\n5. Montar la ensalada: lechuga, pollo, picatostes, queso y salsa.',
    prepTime: 15,
    cookTime: 10,
    servings: 2,
    categories: [MealType.COMIDA, MealType.CENA],
    tags: ['Saludable'],
    ingredients: [
      { name: 'Lechuga romana', quantity: 1, unit: 'unidad' },
      { name: 'Pechuga de pollo', quantity: 1, unit: 'unidad' },
      { name: 'Pan de molde', quantity: 2, unit: 'rebanadas' },
      { name: 'Queso parmesano', quantity: 50, unit: 'g' },
      { name: 'Mayonesa', quantity: 3, unit: 'cucharadas' },
      { name: 'Limón', quantity: 0.5, unit: 'unidad' },
      { name: 'Ajo', quantity: 1, unit: 'diente' },
    ],
  },
  {
    title: 'Lentejas estofadas',
    description: 'Lentejas con verduras, un clásico reconfortante de cuchara.',
    imageUrl: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800',
    instructions: '1. Picar la cebolla, la zanahoria, el pimiento y el ajo.\n2. Sofreír las verduras en una olla con aceite (5 min).\n3. Añadir el pimentón, remover y agregar las lentejas.\n4. Cubrir con agua o caldo (el doble de volumen que las lentejas).\n5. Añadir la hoja de laurel y la patata en trozos.\n6. Cocinar a fuego medio 35-40 minutos hasta que las lentejas estén tiernas.\n7. Salpimentar al gusto.',
    prepTime: 10,
    cookTime: 40,
    servings: 6,
    categories: [MealType.COMIDA],
    tags: ['Comfort food', 'Económico', 'Batch cooking', 'Vegano'],
    ingredients: [
      { name: 'Lentejas', quantity: 400, unit: 'g' },
      { name: 'Cebolla', quantity: 1, unit: 'unidad' },
      { name: 'Zanahoria', quantity: 2, unit: 'unidades' },
      { name: 'Patata', quantity: 2, unit: 'unidades' },
      { name: 'Pimiento verde', quantity: 1, unit: 'unidad' },
      { name: 'Ajo', quantity: 2, unit: 'dientes' },
      { name: 'Pimentón dulce', quantity: 1, unit: 'cucharadita' },
      { name: 'Hoja de laurel', quantity: 1, unit: 'unidad' },
      { name: 'Aceite de oliva', quantity: 30, unit: 'ml' },
      { name: 'Sal', quantity: 1, unit: 'pizca' },
    ],
  },
  {
    title: 'Pasta carbonara',
    description: 'Carbonara cremosa al estilo italiano, sin nata.',
    imageUrl: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800',
    instructions: '1. Cocer la pasta en agua con sal según las instrucciones del paquete.\n2. Mientras, cortar la panceta en tiras y dorarla en una sartén sin aceite.\n3. Batir los huevos con el queso pecorino rallado y pimienta negra.\n4. Escurrir la pasta reservando un poco de agua de cocción.\n5. Fuera del fuego, mezclar la pasta con la panceta.\n6. Añadir la mezcla de huevo y queso, remover rápidamente.\n7. Ajustar la cremosidad con agua de cocción.',
    prepTime: 5,
    cookTime: 15,
    servings: 4,
    categories: [MealType.COMIDA, MealType.CENA],
    tags: ['Rápido', 'Comfort food'],
    ingredients: [
      { name: 'Espaguetis', quantity: 400, unit: 'g' },
      { name: 'Panceta o guanciale', quantity: 200, unit: 'g' },
      { name: 'Huevos', quantity: 4, unit: 'unidades' },
      { name: 'Queso pecorino', quantity: 100, unit: 'g' },
      { name: 'Pimienta negra', quantity: 1, unit: 'cucharadita' },
    ],
  },
  {
    title: 'Bowl de açaí',
    description: 'Bowl energético de açaí con frutas y granola.',
    imageUrl: 'https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800',
    instructions: '1. Triturar la pulpa de açaí congelada con el plátano y la leche.\n2. Verter en un bowl.\n3. Decorar con las fresas cortadas, los arándanos, la granola y el coco.\n4. Añadir la miel por encima.',
    prepTime: 10,
    cookTime: 0,
    servings: 1,
    categories: [MealType.DESAYUNO, MealType.SNACK],
    tags: ['Saludable', 'Rápido'],
    ingredients: [
      { name: 'Pulpa de açaí congelada', quantity: 100, unit: 'g' },
      { name: 'Plátano', quantity: 1, unit: 'unidad' },
      { name: 'Leche vegetal', quantity: 80, unit: 'ml' },
      { name: 'Fresas', quantity: 4, unit: 'unidades' },
      { name: 'Arándanos', quantity: 30, unit: 'g' },
      { name: 'Granola', quantity: 30, unit: 'g' },
      { name: 'Coco rallado', quantity: 10, unit: 'g' },
      { name: 'Miel', quantity: 1, unit: 'cucharada' },
    ],
  },
  {
    title: 'Hummus casero',
    description: 'Hummus cremoso perfecto para picar.',
    imageUrl: 'https://images.unsplash.com/photo-1637949385162-e416fb15b2ad?w=800',
    instructions: '1. Escurrir y enjuagar los garbanzos.\n2. Poner en la batidora los garbanzos, el tahini, el zumo de limón, el ajo y el comino.\n3. Triturar añadiendo agua fría poco a poco hasta conseguir una textura cremosa.\n4. Salpimentar al gusto.\n5. Servir con un chorrito de aceite de oliva y pimentón por encima.',
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    categories: [MealType.SNACK],
    tags: ['Vegano', 'Saludable', 'Sin gluten', 'Rápido'],
    ingredients: [
      { name: 'Garbanzos cocidos', quantity: 400, unit: 'g' },
      { name: 'Tahini', quantity: 3, unit: 'cucharadas' },
      { name: 'Limón', quantity: 1, unit: 'unidad' },
      { name: 'Ajo', quantity: 1, unit: 'diente' },
      { name: 'Comino', quantity: 0.5, unit: 'cucharadita' },
      { name: 'Aceite de oliva', quantity: 30, unit: 'ml' },
      { name: 'Agua fría', quantity: 50, unit: 'ml' },
      { name: 'Sal', quantity: 1, unit: 'pizca' },
      { name: 'Pimentón', quantity: 1, unit: 'pizca' },
    ],
  },
  {
    title: 'Tarta de manzana',
    description: 'Tarta clásica de manzana con canela, sencilla y deliciosa.',
    imageUrl: 'https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?w=800',
    instructions: '1. Precalentar el horno a 180°C.\n2. Pelar las manzanas y cortarlas en láminas finas.\n3. Batir los huevos con el azúcar hasta que estén espumosos.\n4. Añadir la mantequilla derretida y la leche.\n5. Incorporar la harina tamizada y la canela.\n6. Verter la mitad de la masa en un molde engrasado.\n7. Colocar las manzanas y cubrir con el resto de la masa.\n8. Hornear 40 minutos.',
    prepTime: 20,
    cookTime: 40,
    servings: 8,
    categories: [MealType.POSTRE],
    tags: ['Comfort food'],
    ingredients: [
      { name: 'Manzanas', quantity: 4, unit: 'unidades' },
      { name: 'Huevos', quantity: 3, unit: 'unidades' },
      { name: 'Azúcar', quantity: 150, unit: 'g' },
      { name: 'Harina', quantity: 200, unit: 'g' },
      { name: 'Mantequilla', quantity: 100, unit: 'g' },
      { name: 'Leche', quantity: 100, unit: 'ml' },
      { name: 'Canela en polvo', quantity: 1, unit: 'cucharadita' },
    ],
  },
  {
    title: 'Salteado de verduras con tofu',
    description: 'Salteado rápido asiático con tofu crujiente.',
    imageUrl: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800',
    instructions: '1. Escurrir el tofu, cortarlo en cubos y secarlo con papel.\n2. Dorar el tofu en una sartén con aceite de sésamo hasta que esté crujiente.\n3. Retirar el tofu y saltear las verduras cortadas en juliana (3 min a fuego fuerte).\n4. Añadir la salsa de soja, el jengibre y el ajo.\n5. Devolver el tofu a la sartén.\n6. Servir sobre arroz o fideos.',
    prepTime: 15,
    cookTime: 10,
    servings: 2,
    categories: [MealType.COMIDA, MealType.CENA],
    tags: ['Vegano', 'Saludable', 'Rápido'],
    ingredients: [
      { name: 'Tofu firme', quantity: 200, unit: 'g' },
      { name: 'Brócoli', quantity: 150, unit: 'g' },
      { name: 'Zanahoria', quantity: 1, unit: 'unidad' },
      { name: 'Pimiento rojo', quantity: 1, unit: 'unidad' },
      { name: 'Salsa de soja', quantity: 30, unit: 'ml' },
      { name: 'Aceite de sésamo', quantity: 15, unit: 'ml' },
      { name: 'Jengibre fresco', quantity: 10, unit: 'g' },
      { name: 'Ajo', quantity: 2, unit: 'dientes' },
    ],
  },
  {
    title: 'Overnight oats',
    description: 'Avena nocturna lista para desayunar sin cocinar.',
    imageUrl: 'https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=800',
    instructions: '1. Mezclar la avena con la leche, el yogur y la miel en un tarro.\n2. Añadir las semillas de chía.\n3. Tapar y refrigerar toda la noche (mínimo 6 horas).\n4. Por la mañana, añadir fruta fresca y frutos secos.',
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    categories: [MealType.DESAYUNO],
    tags: ['Saludable', 'Rápido', 'Batch cooking'],
    ingredients: [
      { name: 'Copos de avena', quantity: 50, unit: 'g' },
      { name: 'Leche', quantity: 120, unit: 'ml' },
      { name: 'Yogur natural', quantity: 60, unit: 'g' },
      { name: 'Semillas de chía', quantity: 10, unit: 'g' },
      { name: 'Miel', quantity: 1, unit: 'cucharada' },
      { name: 'Plátano', quantity: 0.5, unit: 'unidad' },
      { name: 'Nueces', quantity: 15, unit: 'g' },
    ],
  },
  {
    title: 'Pimientos rellenos de carne',
    description: 'Pimientos asados rellenos de carne picada con arroz.',
    imageUrl: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800',
    instructions: '1. Precalentar el horno a 190°C.\n2. Cortar la parte superior de los pimientos y retirar las semillas.\n3. Sofreír la cebolla y el ajo picados.\n4. Añadir la carne picada y cocinar hasta que esté hecha.\n5. Mezclar con el arroz cocido, el tomate triturado y las especias.\n6. Rellenar los pimientos con la mezcla.\n7. Colocar en una bandeja de horno y hornear 30 minutos.\n8. Añadir queso rallado los últimos 5 minutos.',
    prepTime: 20,
    cookTime: 35,
    servings: 4,
    categories: [MealType.CENA],
    tags: ['Comfort food', 'Batch cooking'],
    ingredients: [
      { name: 'Pimientos grandes', quantity: 4, unit: 'unidades' },
      { name: 'Carne picada', quantity: 400, unit: 'g' },
      { name: 'Arroz cocido', quantity: 150, unit: 'g' },
      { name: 'Cebolla', quantity: 1, unit: 'unidad' },
      { name: 'Ajo', quantity: 2, unit: 'dientes' },
      { name: 'Tomate triturado', quantity: 200, unit: 'ml' },
      { name: 'Queso rallado', quantity: 80, unit: 'g' },
      { name: 'Aceite de oliva', quantity: 20, unit: 'ml' },
      { name: 'Sal', quantity: 1, unit: 'pizca' },
      { name: 'Pimienta', quantity: 1, unit: 'pizca' },
    ],
  },
  {
    title: 'Batido verde energético',
    description: 'Batido de espinacas, plátano y mango lleno de vitaminas.',
    imageUrl: 'https://images.unsplash.com/photo-1638176066666-ffb2f013c7dd?w=800',
    instructions: '1. Poner todos los ingredientes en la batidora.\n2. Triturar hasta obtener una mezcla homogénea.\n3. Servir frío inmediatamente.',
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    categories: [MealType.DESAYUNO, MealType.SNACK],
    tags: ['Vegano', 'Saludable', 'Rápido', 'Sin gluten'],
    ingredients: [
      { name: 'Espinacas frescas', quantity: 30, unit: 'g' },
      { name: 'Plátano', quantity: 1, unit: 'unidad' },
      { name: 'Mango congelado', quantity: 100, unit: 'g' },
      { name: 'Leche vegetal', quantity: 200, unit: 'ml' },
      { name: 'Semillas de lino', quantity: 5, unit: 'g' },
    ],
  },
  {
    title: 'Salmón al horno con verduras',
    description: 'Salmón jugoso al horno con verduras asadas.',
    imageUrl: 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800',
    instructions: '1. Precalentar el horno a 200°C.\n2. Colocar las verduras cortadas en una bandeja con aceite, sal y pimienta.\n3. Hornear las verduras 15 minutos.\n4. Colocar los lomos de salmón sobre las verduras.\n5. Aliñar el salmón con limón, eneldo y aceite.\n6. Hornear 12-15 minutos más.',
    prepTime: 10,
    cookTime: 30,
    servings: 2,
    categories: [MealType.CENA],
    tags: ['Saludable', 'Sin gluten'],
    ingredients: [
      { name: 'Lomos de salmón', quantity: 2, unit: 'unidades' },
      { name: 'Calabacín', quantity: 1, unit: 'unidad' },
      { name: 'Tomates cherry', quantity: 150, unit: 'g' },
      { name: 'Cebolla morada', quantity: 1, unit: 'unidad' },
      { name: 'Limón', quantity: 1, unit: 'unidad' },
      { name: 'Eneldo fresco', quantity: 5, unit: 'g' },
      { name: 'Aceite de oliva', quantity: 30, unit: 'ml' },
      { name: 'Sal', quantity: 1, unit: 'pizca' },
      { name: 'Pimienta', quantity: 1, unit: 'pizca' },
    ],
  },
  {
    title: 'Paella valenciana',
    description: 'Arroz tradicional valenciano con pollo, conejo y verduras.',
    imageUrl: 'https://images.unsplash.com/photo-1534080564583-6be75777b70a?w=800',
    instructions: '1. Calentar aceite en una paellera y dorar el pollo y el conejo troceados.\n2. Añadir las judías verdes y el garrofón, sofreír 2 min.\n3. Agregar el tomate rallado y el pimentón, remover.\n4. Cubrir con agua y cocer 20 min.\n5. Añadir el arroz, el azafrán y la sal.\n6. Cocinar a fuego fuerte 10 min y después medio 8 min.\n7. Dejar reposar 5 min antes de servir.',
    prepTime: 20,
    cookTime: 45,
    servings: 6,
    categories: [MealType.COMIDA],
    tags: ['Sin gluten', 'Comfort food'],
    ingredients: [
      { name: 'Arroz bomba', quantity: 400, unit: 'g' },
      { name: 'Pollo troceado', quantity: 500, unit: 'g' },
      { name: 'Conejo troceado', quantity: 400, unit: 'g' },
      { name: 'Judías verdes', quantity: 200, unit: 'g' },
      { name: 'Tomate rallado', quantity: 100, unit: 'g' },
      { name: 'Azafrán', quantity: 1, unit: 'pizca' },
      { name: 'Pimentón dulce', quantity: 1, unit: 'cucharadita' },
      { name: 'Aceite de oliva', quantity: 60, unit: 'ml' },
      { name: 'Sal', quantity: 1, unit: 'pizca' },
    ],
  },
  {
    title: 'Tacos de pollo',
    description: 'Tacos caseros con pollo marinado, aguacate y pico de gallo.',
    imageUrl: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800',
    instructions: '1. Marinar el pollo con comino, pimentón, ajo y limón (30 min).\n2. Cocinar el pollo en una sartén a fuego fuerte hasta dorar.\n3. Cortar en tiras.\n4. Preparar pico de gallo: tomate, cebolla, cilantro, limón y sal.\n5. Calentar las tortillas.\n6. Montar: tortilla, pollo, aguacate en láminas y pico de gallo.',
    prepTime: 40,
    cookTime: 10,
    servings: 4,
    categories: [MealType.CENA, MealType.COMIDA],
    tags: ['Rápido'],
    ingredients: [
      { name: 'Pechuga de pollo', quantity: 500, unit: 'g' },
      { name: 'Tortillas de maíz', quantity: 8, unit: 'unidades' },
      { name: 'Aguacate', quantity: 2, unit: 'unidades' },
      { name: 'Tomate', quantity: 2, unit: 'unidades' },
      { name: 'Cebolla morada', quantity: 0.5, unit: 'unidad' },
      { name: 'Cilantro fresco', quantity: 10, unit: 'g' },
      { name: 'Limón', quantity: 2, unit: 'unidades' },
      { name: 'Comino', quantity: 1, unit: 'cucharadita' },
      { name: 'Pimentón', quantity: 1, unit: 'cucharadita' },
    ],
  },
  {
    title: 'Crema de calabaza',
    description: 'Crema suave y reconfortante de calabaza asada.',
    imageUrl: 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=800',
    instructions: '1. Precalentar el horno a 200°C.\n2. Cortar la calabaza en trozos y asar con aceite 25 min.\n3. Sofreír la cebolla y el ajo en una olla.\n4. Añadir la calabaza asada y el caldo.\n5. Cocinar 10 min y triturar hasta obtener una crema suave.\n6. Salpimentar y servir con un chorrito de aceite y semillas.',
    prepTime: 10,
    cookTime: 35,
    servings: 4,
    categories: [MealType.CENA, MealType.COMIDA],
    tags: ['Vegano', 'Sin gluten', 'Saludable', 'Batch cooking'],
    ingredients: [
      { name: 'Calabaza', quantity: 800, unit: 'g' },
      { name: 'Cebolla', quantity: 1, unit: 'unidad' },
      { name: 'Ajo', quantity: 2, unit: 'dientes' },
      { name: 'Caldo de verduras', quantity: 500, unit: 'ml' },
      { name: 'Aceite de oliva', quantity: 30, unit: 'ml' },
      { name: 'Sal', quantity: 1, unit: 'pizca' },
      { name: 'Pimienta', quantity: 1, unit: 'pizca' },
      { name: 'Semillas de calabaza', quantity: 20, unit: 'g' },
    ],
  },
  {
    title: 'Risotto de champiñones',
    description: 'Risotto cremoso con champiñones y parmesano.',
    imageUrl: 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=800',
    instructions: '1. Calentar el caldo y mantenerlo a fuego bajo.\n2. Sofreír la cebolla picada en mantequilla.\n3. Añadir el arroz y tostar 2 min.\n4. Agregar el vino blanco y dejar evaporar.\n5. Ir añadiendo caldo cucharón a cucharón, removiendo constantemente.\n6. En otra sartén, saltear los champiñones con ajo.\n7. Cuando el arroz esté al dente (~18 min), añadir los champiñones, mantequilla y parmesano.',
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    categories: [MealType.COMIDA, MealType.CENA],
    tags: ['Comfort food'],
    ingredients: [
      { name: 'Arroz arborio', quantity: 320, unit: 'g' },
      { name: 'Champiñones', quantity: 300, unit: 'g' },
      { name: 'Caldo de verduras', quantity: 1, unit: 'litro' },
      { name: 'Cebolla', quantity: 1, unit: 'unidad' },
      { name: 'Vino blanco', quantity: 100, unit: 'ml' },
      { name: 'Mantequilla', quantity: 40, unit: 'g' },
      { name: 'Queso parmesano', quantity: 80, unit: 'g' },
      { name: 'Ajo', quantity: 2, unit: 'dientes' },
      { name: 'Aceite de oliva', quantity: 20, unit: 'ml' },
    ],
  },
  {
    title: 'Tortitas de avena y plátano',
    description: 'Tortitas saludables con solo 3 ingredientes base.',
    imageUrl: 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=800',
    instructions: '1. Triturar la avena hasta hacerla harina.\n2. Mezclar con el plátano machacado y los huevos.\n3. Calentar una sartén antiadherente con un poco de aceite.\n4. Verter porciones de masa y cocinar 2 min por lado.\n5. Servir con fruta fresca, miel o yogur.',
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    categories: [MealType.DESAYUNO, MealType.SNACK],
    tags: ['Saludable', 'Rápido', 'Sin gluten'],
    ingredients: [
      { name: 'Copos de avena', quantity: 80, unit: 'g' },
      { name: 'Plátano maduro', quantity: 1, unit: 'unidad' },
      { name: 'Huevos', quantity: 2, unit: 'unidades' },
      { name: 'Canela', quantity: 0.5, unit: 'cucharadita' },
      { name: 'Aceite de coco', quantity: 5, unit: 'ml' },
    ],
  },
  {
    title: 'Curry de garbanzos',
    description: 'Curry vegano cremoso con garbanzos y leche de coco.',
    imageUrl: 'https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=800',
    instructions: '1. Sofreír la cebolla y el ajo picados en aceite.\n2. Añadir el jengibre rallado y el curry en polvo, cocinar 1 min.\n3. Agregar los tomates triturados y cocinar 5 min.\n4. Añadir los garbanzos escurridos y la leche de coco.\n5. Cocinar a fuego medio 15 min.\n6. Añadir las espinacas al final y dejar que se marchiten.\n7. Servir con arroz basmati.',
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    categories: [MealType.COMIDA, MealType.CENA],
    tags: ['Vegano', 'Saludable', 'Sin gluten', 'Batch cooking'],
    ingredients: [
      { name: 'Garbanzos cocidos', quantity: 400, unit: 'g' },
      { name: 'Leche de coco', quantity: 400, unit: 'ml' },
      { name: 'Tomate triturado', quantity: 200, unit: 'g' },
      { name: 'Espinacas', quantity: 100, unit: 'g' },
      { name: 'Cebolla', quantity: 1, unit: 'unidad' },
      { name: 'Ajo', quantity: 3, unit: 'dientes' },
      { name: 'Jengibre fresco', quantity: 10, unit: 'g' },
      { name: 'Curry en polvo', quantity: 2, unit: 'cucharadas' },
      { name: 'Arroz basmati', quantity: 300, unit: 'g' },
    ],
  },
  {
    title: 'Croquetas de jamón',
    description: 'Croquetas caseras cremosas de jamón serrano.',
    imageUrl: 'https://images.unsplash.com/photo-1554520735-0a6b8b6ce8b7?w=800',
    instructions: '1. Derretir la mantequilla y sofreír la cebolla picada fina.\n2. Añadir la harina y remover 2 min (roux).\n3. Ir añadiendo la leche caliente poco a poco, sin dejar de remover.\n4. Cocinar la bechamel 10 min a fuego bajo.\n5. Añadir el jamón picado fino y nuez moscada.\n6. Verter en una bandeja, cubrir con film y refrigerar 4 horas.\n7. Formar las croquetas, pasar por huevo y pan rallado.\n8. Freír en aceite caliente hasta dorar.',
    prepTime: 30,
    cookTime: 20,
    servings: 6,
    categories: [MealType.CENA, MealType.SNACK],
    tags: ['Comfort food', 'Batch cooking'],
    ingredients: [
      { name: 'Jamón serrano', quantity: 150, unit: 'g' },
      { name: 'Mantequilla', quantity: 80, unit: 'g' },
      { name: 'Harina', quantity: 80, unit: 'g' },
      { name: 'Leche entera', quantity: 750, unit: 'ml' },
      { name: 'Cebolla', quantity: 0.5, unit: 'unidad' },
      { name: 'Nuez moscada', quantity: 1, unit: 'pizca' },
      { name: 'Huevos', quantity: 2, unit: 'unidades' },
      { name: 'Pan rallado', quantity: 150, unit: 'g' },
      { name: 'Aceite de girasol', quantity: 500, unit: 'ml' },
    ],
  },
  {
    title: 'Ensalada de quinoa',
    description: 'Ensalada fresca y nutritiva con quinoa, aguacate y verduras.',
    imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800',
    instructions: '1. Cocer la quinoa en agua con sal 15 min, escurrir y dejar enfriar.\n2. Cortar el pepino, los tomates cherry, el aguacate y la cebolla morada.\n3. Mezclar todo en un bol grande.\n4. Aliñar con aceite de oliva, limón, sal y pimienta.\n5. Añadir las hojas de menta fresca.',
    prepTime: 10,
    cookTime: 15,
    servings: 3,
    categories: [MealType.COMIDA, MealType.CENA],
    tags: ['Vegano', 'Saludable', 'Sin gluten'],
    ingredients: [
      { name: 'Quinoa', quantity: 200, unit: 'g' },
      { name: 'Aguacate', quantity: 1, unit: 'unidad' },
      { name: 'Tomates cherry', quantity: 150, unit: 'g' },
      { name: 'Pepino', quantity: 1, unit: 'unidad' },
      { name: 'Cebolla morada', quantity: 0.5, unit: 'unidad' },
      { name: 'Menta fresca', quantity: 10, unit: 'g' },
      { name: 'Aceite de oliva', quantity: 30, unit: 'ml' },
      { name: 'Limón', quantity: 1, unit: 'unidad' },
      { name: 'Sal', quantity: 1, unit: 'pizca' },
    ],
  },
  {
    title: 'Pizza casera de masa madre',
    description: 'Pizza crujiente con masa casera y toppings al gusto.',
    imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800',
    instructions: '1. Mezclar la harina con la levadura, el agua tibia, el aceite y la sal.\n2. Amasar 10 min hasta obtener una masa elástica.\n3. Dejar reposar tapada 1 hora.\n4. Precalentar el horno a 250°C.\n5. Estirar la masa sobre una bandeja enharinada.\n6. Untar la salsa de tomate, añadir la mozzarella y los toppings.\n7. Hornear 10-12 min hasta que esté dorada.',
    prepTime: 75,
    cookTime: 12,
    servings: 4,
    categories: [MealType.CENA, MealType.COMIDA],
    tags: ['Comfort food'],
    ingredients: [
      { name: 'Harina de fuerza', quantity: 500, unit: 'g' },
      { name: 'Levadura fresca', quantity: 25, unit: 'g' },
      { name: 'Agua tibia', quantity: 300, unit: 'ml' },
      { name: 'Aceite de oliva', quantity: 30, unit: 'ml' },
      { name: 'Sal', quantity: 10, unit: 'g' },
      { name: 'Salsa de tomate', quantity: 200, unit: 'g' },
      { name: 'Mozzarella fresca', quantity: 250, unit: 'g' },
      { name: 'Albahaca fresca', quantity: 10, unit: 'hojas' },
    ],
  },
  {
    title: 'Brownie de chocolate',
    description: 'Brownie denso y jugoso con trozos de chocolate.',
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800',
    instructions: '1. Precalentar el horno a 180°C.\n2. Derretir el chocolate con la mantequilla al baño maría.\n3. Batir los huevos con el azúcar hasta que dupliquen volumen.\n4. Incorporar la mezcla de chocolate templada.\n5. Añadir la harina tamizada y mezclar con movimientos envolventes.\n6. Verter en un molde engrasado y forrado.\n7. Hornear 22-25 min (que quede húmedo por dentro).\n8. Dejar enfriar antes de cortar.',
    prepTime: 15,
    cookTime: 25,
    servings: 9,
    categories: [MealType.POSTRE, MealType.SNACK],
    tags: ['Comfort food'],
    ingredients: [
      { name: 'Chocolate negro 70%', quantity: 200, unit: 'g' },
      { name: 'Mantequilla', quantity: 150, unit: 'g' },
      { name: 'Huevos', quantity: 3, unit: 'unidades' },
      { name: 'Azúcar', quantity: 180, unit: 'g' },
      { name: 'Harina', quantity: 80, unit: 'g' },
      { name: 'Sal', quantity: 1, unit: 'pizca' },
    ],
  },
];
