type MealType = 'DESAYUNO' | 'COMIDA' | 'CENA' | 'SNACK';

const IMG = {
  salmon:    'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?auto=format&fit=crop&w=400&q=80',
  pollo:     'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=400&q=80',
  huevos:    'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=400&q=80',
  pasta:     'https://images.unsplash.com/photo-1608219992759-8d74ed8d76eb?auto=format&fit=crop&w=400&q=80',
  arroz:     'https://images.unsplash.com/photo-1516684732162-798a0062be99?auto=format&fit=crop&w=400&q=80',
  porridge:  'https://images.unsplash.com/photo-1584278860047-22db9ff82bed?auto=format&fit=crop&w=400&q=80',
  yogurt:    'https://images.unsplash.com/photo-1571212515416-fef01fc43637?auto=format&fit=crop&w=400&q=80',
  toast:     'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80',
  bowl:      'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=400&q=80',
  ensalada:  'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=400&q=80',
  chocolate: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=400&q=80',
  banana:    'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=400&q=80',
  pancakes:  'https://images.unsplash.com/photo-1506084868230-bb9d95c24759?auto=format&fit=crop&w=400&q=80',
  noquis:    'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?auto=format&fit=crop&w=400&q=80',
};

export interface MenuRecipe {
  title: string;
  description: string;
  instructions: string;
  prepTime: number;
  cookTime: number;
  servings: number;
  kcal: number;
  imageUrl: string;
  categories: MealType[];
  ingredients: { name: string; quantity?: number | null; unit?: string | null }[];
}

export const menuRecipes: MenuRecipe[] = [
  // ─── DESAYUNOS ────────────────────────────────────────────────────────────
  {
    title: 'Pan cristal + pavo + aceite',
    description: 'Desayuno clásico con proteína. Controla la ración de aceite (~90 kcal por cucharada).',
    instructions: 'Poner 2 lonchas de pavo sobre pan cristal. Añadir 1 cucharada de aceite de oliva. Acompañar con ColaCao Zero con leche.',
    prepTime: 5, cookTime: 0, servings: 1, kcal: 380, imageUrl: IMG.toast,
    categories: ['DESAYUNO'],
    ingredients: [
      { name: 'Pan cristal', quantity: 1, unit: 'rebanada' },
      { name: 'Pavo en lonchas', quantity: 2, unit: 'lonchas' },
      { name: 'Aceite de oliva', quantity: 1, unit: 'cucharada' },
      { name: 'ColaCao Zero', quantity: 1, unit: 'cucharada' },
      { name: 'Leche', quantity: 200, unit: 'ml' },
    ],
  },
  {
    title: 'Porridge proteico',
    description: 'Desayuno de gym: carbohidratos de calidad, proteína y grasa saludable.',
    instructions: 'Mezclar la avena con la leche. Calentar 2-3 minutos en microondas. Añadir plátano troceado y mantequilla de cacahuete por encima.',
    prepTime: 2, cookTime: 5, servings: 1, kcal: 430, imageUrl: IMG.porridge,
    categories: ['DESAYUNO'],
    ingredients: [
      { name: 'Avena', quantity: 60, unit: 'g' },
      { name: 'Leche', quantity: 200, unit: 'ml' },
      { name: 'Plátano', quantity: 1, unit: 'unidad' },
      { name: 'Mantequilla de cacahuete', quantity: 1, unit: 'cucharada' },
    ],
  },
  {
    title: 'Pan cristal + pavo + aguacate',
    description: 'Con grasa saludable del aguacate. Limita el guacamole a 2-3 cucharadas.',
    instructions: 'Poner 2 lonchas de pavo sobre pan cristal. Añadir 3 cucharadas de guacamole Mercadona. Acompañar con café.',
    prepTime: 5, cookTime: 0, servings: 1, kcal: 400, imageUrl: IMG.toast,
    categories: ['DESAYUNO'],
    ingredients: [
      { name: 'Pan cristal', quantity: 1, unit: 'rebanada' },
      { name: 'Pavo en lonchas', quantity: 2, unit: 'lonchas' },
      { name: 'Guacamole Mercadona', quantity: 3, unit: 'cucharadas' },
    ],
  },
  {
    title: 'Yogur griego + fruta + MPC',
    description: 'Rápido, proteico y saciante. Perfecto cuando tienes poco tiempo.',
    instructions: 'Poner el yogur griego en un bol. Añadir plátano o fresas troceadas. Una cucharada de mantequilla de cacahuete por encima.',
    prepTime: 5, cookTime: 0, servings: 1, kcal: 350, imageUrl: IMG.yogurt,
    categories: ['DESAYUNO'],
    ingredients: [
      { name: 'Yogur griego natural', quantity: 200, unit: 'g' },
      { name: 'Plátano o fresas', quantity: 1, unit: 'unidad' },
      { name: 'Mantequilla de cacahuete', quantity: 1, unit: 'cucharada' },
    ],
  },
  // ─── COMIDAS ──────────────────────────────────────────────────────────────
  {
    title: 'Salmón air fryer + arroz',
    description: 'Plato completo de día de gym. Proteína + carbohidratos + Omega-3.',
    instructions: 'Cocinar el salmón en air fryer a 200 °C, 10-12 min. Preparar 150 g de arroz cocido. Asar calabacín con aceite. Rallar grana padano al servir.',
    prepTime: 10, cookTime: 20, servings: 1, kcal: 520, imageUrl: IMG.salmon,
    categories: ['COMIDA'],
    ingredients: [
      { name: 'Filete de salmón', quantity: 150, unit: 'g' },
      { name: 'Arroz cocido', quantity: 150, unit: 'g' },
      { name: 'Calabacín', quantity: 1, unit: 'unidad' },
      { name: 'Grana padano', quantity: 1, unit: 'cucharada' },
      { name: 'Aceite de oliva', quantity: 1, unit: 'cucharada' },
    ],
  },
  {
    title: 'Pollo air fryer + zanahoria asada',
    description: 'Alto en proteína, bajo en carbohidratos. Ideal para días de descanso.',
    instructions: 'Sazonar la pechuga con especias. Cocinar en air fryer a 200 °C, 20 min dando la vuelta a mitad. Zanahoria en bastones con aceite y sal al mismo tiempo.',
    prepTime: 10, cookTime: 20, servings: 1, kcal: 400, imageUrl: IMG.pollo,
    categories: ['COMIDA'],
    ingredients: [
      { name: 'Pechuga de pollo', quantity: 200, unit: 'g' },
      { name: 'Zanahoria', quantity: 2, unit: 'unidades' },
      { name: 'Aceite de oliva', quantity: 1, unit: 'cucharada' },
      { name: 'Especias al gusto', quantity: null, unit: null },
    ],
  },
  {
    title: 'Bowl de pollo + arroz',
    description: 'Bowl equilibrado para después de entrenar. Pollo, arroz y verdura.',
    instructions: 'Trocear y saltear el pollo con aceite. Cocer arroz. Saltear calabacín. Montar: arroz de base, pollo encima, calabacín al lado. Grana padano rallado.',
    prepTime: 10, cookTime: 20, servings: 1, kcal: 500, imageUrl: IMG.bowl,
    categories: ['COMIDA'],
    ingredients: [
      { name: 'Pechuga de pollo troceada', quantity: 200, unit: 'g' },
      { name: 'Arroz cocido', quantity: 150, unit: 'g' },
      { name: 'Calabacín', quantity: 1, unit: 'unidad' },
      { name: 'Grana padano', quantity: 1, unit: 'cucharada' },
    ],
  },
  {
    title: 'Huevos al horno + calabacín',
    description: 'Plato saciante sin carbohidratos. En cazuela al air fryer, listo en 10 minutos.',
    instructions: 'Trocear calabacín y tomate en cazuela apta para air fryer. Cascar 3 huevos encima. Air fryer a 180 °C, 10 min. Acompañar con pan cristal.',
    prepTime: 10, cookTime: 10, servings: 1, kcal: 480, imageUrl: IMG.huevos,
    categories: ['COMIDA'],
    ingredients: [
      { name: 'Huevos', quantity: 3, unit: 'unidades' },
      { name: 'Calabacín', quantity: 1, unit: 'unidad' },
      { name: 'Tomate', quantity: 1, unit: 'unidad' },
      { name: 'Pan cristal', quantity: 1, unit: 'rebanada' },
    ],
  },
  {
    title: 'Ñoquis + salmón + mozzarella bolitas',
    description: 'Ñoquis solo en días de gym o cardio. Ración máxima 150-200 g cocidos.',
    instructions: 'Cocer 150 g de ñoquis. Saltear el salmón en trozos. Mezclar ñoquis, salmón, mozzarella bolitas y calabacín troceado. Servir caliente.',
    prepTime: 10, cookTime: 15, servings: 1, kcal: 520, imageUrl: IMG.noquis,
    categories: ['COMIDA'],
    ingredients: [
      { name: 'Ñoquis', quantity: 150, unit: 'g' },
      { name: 'Salmón', quantity: 120, unit: 'g' },
      { name: 'Mozzarella bolitas', quantity: 80, unit: 'g' },
      { name: 'Calabacín', quantity: 1, unit: 'unidad' },
    ],
  },
  {
    title: 'Pollo al horno + verduras (batch)',
    description: 'Batch cooking del sábado. Prepara 3-4 pechugas y tienes comida para toda la semana.',
    instructions: 'Colocar pechugas y verduras en bandeja. Aceite, sal y especias. Horno a 200 °C, 35-40 min. Guardar en recipientes en la nevera.',
    prepTime: 15, cookTime: 40, servings: 4, kcal: 480, imageUrl: IMG.pollo,
    categories: ['COMIDA'],
    ingredients: [
      { name: 'Pechugas de pollo', quantity: 800, unit: 'g' },
      { name: 'Zanahoria', quantity: 2, unit: 'unidades' },
      { name: 'Calabacín', quantity: 2, unit: 'unidades' },
      { name: 'Aceite de oliva', quantity: 2, unit: 'cucharadas' },
    ],
  },
  {
    title: 'Pasta con atún y tomate',
    description: 'Clásico rápido de toda la vida. Proteína del atún, carbohidrato de la pasta.',
    instructions: 'Cocer la pasta. Calentar tomate triturado con ajo y aceite. Escurrir el atún y añadir a la salsa. Mezclar con la pasta. Grana padano al servir.',
    prepTime: 5, cookTime: 15, servings: 1, kcal: 490, imageUrl: IMG.pasta,
    categories: ['COMIDA'],
    ingredients: [
      { name: 'Pasta', quantity: 80, unit: 'g' },
      { name: 'Atún en lata', quantity: 2, unit: 'latas' },
      { name: 'Tomate triturado', quantity: 200, unit: 'ml' },
      { name: 'Ajo', quantity: 1, unit: 'diente' },
      { name: 'Aceite de oliva', quantity: 1, unit: 'cucharada' },
    ],
  },
  {
    title: 'Pasta con salmón y calabacín',
    description: 'Suave y ligera. El agua de cocción de la pasta liga la salsa sin nata.',
    instructions: 'Cocer la pasta. Saltear calabacín con aceite. Añadir salmón en trozos, cocinar 3-4 min. Mezclar con la pasta y un poco del agua de cocción. Grana padano al final.',
    prepTime: 5, cookTime: 15, servings: 1, kcal: 510, imageUrl: IMG.pasta,
    categories: ['COMIDA'],
    ingredients: [
      { name: 'Pasta', quantity: 80, unit: 'g' },
      { name: 'Filete de salmón', quantity: 130, unit: 'g' },
      { name: 'Calabacín', quantity: 1, unit: 'unidad' },
      { name: 'Aceite de oliva', quantity: 1, unit: 'cucharada' },
      { name: 'Grana padano', quantity: 1, unit: 'cucharada' },
    ],
  },
  {
    title: 'Pasta con pavo y mozzarella',
    description: 'Alta en proteína, fácil y en 20 minutos. La mozzarella se funde con el calor.',
    instructions: 'Cocer la pasta. Saltear el pavo en tiras con aceite. Mezclar pasta con el pavo. Mozzarella rallada encima y dejar fundir un momento antes de servir.',
    prepTime: 5, cookTime: 15, servings: 1, kcal: 500, imageUrl: IMG.pasta,
    categories: ['COMIDA'],
    ingredients: [
      { name: 'Pasta', quantity: 80, unit: 'g' },
      { name: 'Pavo en tiras', quantity: 120, unit: 'g' },
      { name: 'Mozzarella rallada', quantity: 40, unit: 'g' },
      { name: 'Aceite de oliva', quantity: 1, unit: 'cucharada' },
    ],
  },
  {
    title: 'Carbonara light con grana padano',
    description: 'Sin nata. El huevo y el queso hacen la salsa cremosa — la pasta cocina el huevo.',
    instructions: 'Cocer la pasta guardando un vaso del agua de cocción. Batir 2 huevos con grana padano y pimienta. Fuera del fuego, mezclar pasta caliente con la mezcla de huevo removiendo rápido.',
    prepTime: 5, cookTime: 15, servings: 1, kcal: 480, imageUrl: IMG.pasta,
    categories: ['COMIDA'],
    ingredients: [
      { name: 'Pasta', quantity: 80, unit: 'g' },
      { name: 'Huevos', quantity: 2, unit: 'unidades' },
      { name: 'Grana padano', quantity: 2, unit: 'cucharadas' },
      { name: 'Pimienta negra', quantity: null, unit: null },
    ],
  },
  {
    title: 'Arroz con atún y zanahoria',
    description: 'Sencillo, económico y completo. Listo en el tiempo que tarda el arroz.',
    instructions: 'Cocer el arroz. Saltear zanahoria rallada en sartén con aceite. Escurrir el atún. Mezclar todo y aliñar con limón.',
    prepTime: 5, cookTime: 20, servings: 1, kcal: 460, imageUrl: IMG.arroz,
    categories: ['COMIDA'],
    ingredients: [
      { name: 'Arroz cocido', quantity: 150, unit: 'g' },
      { name: 'Atún en lata', quantity: 2, unit: 'latas' },
      { name: 'Zanahoria', quantity: 1, unit: 'unidad' },
      { name: 'Aceite de oliva', quantity: 1, unit: 'cucharada' },
      { name: 'Limón', quantity: 0.5, unit: 'unidad' },
    ],
  },
  {
    title: 'Arroz con salmón y calabacín',
    description: 'Plato completo con Omega-3. Versión bowl con todo en el mismo plato.',
    instructions: 'Cocer el arroz. Cocinar el salmón en air fryer o sartén. Saltear calabacín con aceite y ajo. Montar en bol con el arroz de base.',
    prepTime: 10, cookTime: 20, servings: 1, kcal: 520, imageUrl: IMG.arroz,
    categories: ['COMIDA'],
    ingredients: [
      { name: 'Arroz cocido', quantity: 150, unit: 'g' },
      { name: 'Filete de salmón', quantity: 130, unit: 'g' },
      { name: 'Calabacín', quantity: 1, unit: 'unidad' },
      { name: 'Aceite de oliva', quantity: 1, unit: 'cucharada' },
      { name: 'Ajo', quantity: 1, unit: 'diente' },
    ],
  },
  {
    title: 'Arroz tres delicias light',
    description: 'Versión saludable del clásico. Mejor con arroz frío del día anterior.',
    instructions: 'En wok con poco aceite, saltear zanahoria picada y guisantes. Añadir los huevos batidos y revolver. Incorporar el arroz frío y saltear todo junto 3-4 min.',
    prepTime: 5, cookTime: 10, servings: 1, kcal: 430, imageUrl: IMG.arroz,
    categories: ['COMIDA'],
    ingredients: [
      { name: 'Arroz cocido frío', quantity: 150, unit: 'g' },
      { name: 'Huevos', quantity: 2, unit: 'unidades' },
      { name: 'Zanahoria', quantity: 1, unit: 'unidad' },
      { name: 'Guisantes', quantity: 50, unit: 'g' },
      { name: 'Aceite de oliva', quantity: 1, unit: 'cucharada' },
    ],
  },
  // ─── CENAS ────────────────────────────────────────────────────────────────
  {
    title: 'Tortilla de calabacín',
    description: 'Cena ligera y proteica. En air fryer queda jugosa por dentro y crujiente por fuera.',
    instructions: 'Rallar el calabacín fino. Batir 3 huevos con sal. Mezclar con calabacín y queso light. Air fryer a 180 °C, 12 min — o sartén antiadherente tapada.',
    prepTime: 10, cookTime: 12, servings: 1, kcal: 320, imageUrl: IMG.huevos,
    categories: ['CENA'],
    ingredients: [
      { name: 'Huevos', quantity: 3, unit: 'unidades' },
      { name: 'Calabacín', quantity: 1, unit: 'unidad' },
      { name: 'Queso light', quantity: 30, unit: 'g' },
    ],
  },
  {
    title: 'Ñoquis + pavo + mozzarella',
    description: 'Cena de recuperación post-cardio. Los carbohidratos reponen el glucógeno.',
    instructions: 'Cocer 150 g de ñoquis. Saltear pavo en tiras. Mezclar ñoquis, pavo, calabacín salteado. Mozzarella rallada encima y servir caliente.',
    prepTime: 10, cookTime: 15, servings: 1, kcal: 480, imageUrl: IMG.noquis,
    categories: ['CENA'],
    ingredients: [
      { name: 'Ñoquis', quantity: 150, unit: 'g' },
      { name: 'Pavo en tiras', quantity: 100, unit: 'g' },
      { name: 'Mozzarella rallada', quantity: 50, unit: 'g' },
      { name: 'Calabacín', quantity: 1, unit: 'unidad' },
    ],
  },
  {
    title: 'Salmón marinado + ensalada',
    description: 'Cena sin cocinar, lista en 5 minutos. Proteína + verdura, sin carbohidratos.',
    instructions: 'Servir el salmón marinado directamente. Preparar ensalada con zanahoria rallada, aceite y zumo de limón.',
    prepTime: 5, cookTime: 0, servings: 1, kcal: 380, imageUrl: IMG.salmon,
    categories: ['CENA'],
    ingredients: [
      { name: 'Salmón marinado', quantity: 150, unit: 'g' },
      { name: 'Zanahoria', quantity: 1, unit: 'unidad' },
      { name: 'Aceite de oliva', quantity: 1, unit: 'cucharada' },
      { name: 'Limón', quantity: 0.5, unit: 'unidad' },
    ],
  },
  {
    title: 'Salmón + calabacín asado',
    description: 'Cena sabrosa y ligera. El ajo con el calabacín en air fryer es una combinación ganadora.',
    instructions: 'Salmón en air fryer a 200 °C, 10-12 min. Calabacín en rodajas con aceite y ajo laminado, al air fryer al mismo tiempo.',
    prepTime: 5, cookTime: 15, servings: 1, kcal: 400, imageUrl: IMG.salmon,
    categories: ['CENA'],
    ingredients: [
      { name: 'Filete de salmón', quantity: 150, unit: 'g' },
      { name: 'Calabacín', quantity: 1, unit: 'unidad' },
      { name: 'Aceite de oliva', quantity: 1, unit: 'cucharada' },
      { name: 'Ajo', quantity: 1, unit: 'diente' },
    ],
  },
  {
    title: 'Huevos revueltos + ensalada zanahoria',
    description: 'Cena rápida post-cardio. Proteína + verdura, en menos de 10 minutos.',
    instructions: 'Batir 2-3 huevos y hacer revuelto cremoso en sartén a fuego medio. Preparar ensalada de zanahoria rallada con limón y aceite.',
    prepTime: 5, cookTime: 5, servings: 1, kcal: 380, imageUrl: IMG.huevos,
    categories: ['CENA'],
    ingredients: [
      { name: 'Huevos', quantity: 3, unit: 'unidades' },
      { name: 'Zanahoria', quantity: 1, unit: 'unidad' },
      { name: 'Limón', quantity: 0.5, unit: 'unidad' },
      { name: 'Aceite de oliva', quantity: 1, unit: 'cucharada' },
    ],
  },
  {
    title: 'Salmón + ensalada ligera',
    description: 'Cena de día de descanso. Ligera, proteica y sin carbohidratos.',
    instructions: 'Salmón marinado directo o a la plancha 3-4 min por lado. Ensalada de zanahoria con aceite de oliva.',
    prepTime: 5, cookTime: 5, servings: 1, kcal: 360, imageUrl: IMG.salmon,
    categories: ['CENA'],
    ingredients: [
      { name: 'Salmón marinado o plancha', quantity: 150, unit: 'g' },
      { name: 'Zanahoria', quantity: 1, unit: 'unidad' },
      { name: 'Aceite de oliva', quantity: 1, unit: 'cucharada' },
    ],
  },
  {
    title: 'Bowl del batch cook',
    description: 'Cena sin cocinar. Con lo preparado el sábado, montas el bol en 2 minutos.',
    instructions: 'Sacar el pollo y las verduras de la nevera. Añadir un poco de arroz y mozzarella. Calentar si se quiere y servir.',
    prepTime: 5, cookTime: 0, servings: 1, kcal: 380, imageUrl: IMG.bowl,
    categories: ['CENA'],
    ingredients: [
      { name: 'Pollo del batch cook', quantity: 150, unit: 'g' },
      { name: 'Arroz cocido', quantity: 80, unit: 'g' },
      { name: 'Mozzarella', quantity: 50, unit: 'g' },
    ],
  },
  // ─── SNACKS ───────────────────────────────────────────────────────────────
  {
    title: 'Yogur griego + plátano + MPC',
    description: 'Post-gym ideal. Proteína del yogur + carbohidrato del plátano para recuperar músculo.',
    instructions: 'Yogur griego en bol, plátano troceado encima y cucharada de mantequilla de cacahuete. Consumir justo después del entreno.',
    prepTime: 3, cookTime: 0, servings: 1, kcal: 280, imageUrl: IMG.yogurt,
    categories: ['SNACK'],
    ingredients: [
      { name: 'Yogur griego natural', quantity: 200, unit: 'g' },
      { name: 'Plátano', quantity: 1, unit: 'unidad' },
      { name: 'Mantequilla de cacahuete', quantity: 1, unit: 'cucharada' },
    ],
  },
  {
    title: 'Yogur con fruta',
    description: 'Snack ligero para días de descanso.',
    instructions: 'Yogur griego natural con fruta a elegir.',
    prepTime: 2, cookTime: 0, servings: 1, kcal: 150, imageUrl: IMG.yogurt,
    categories: ['SNACK'],
    ingredients: [
      { name: 'Yogur griego natural', quantity: 200, unit: 'g' },
      { name: 'Fruta a elegir', quantity: 1, unit: 'unidad' },
    ],
  },
  {
    title: 'Mousse de chocolate proteico',
    description: '~20 g proteína. Parece postre de verdad — nevera 10 min y listo.',
    instructions: 'Mezclar proteína en polvo de chocolate con yogur griego y un poco de leche hasta que quede cremoso. Meter en la nevera 10 minutos.',
    prepTime: 5, cookTime: 0, servings: 1, kcal: 150, imageUrl: IMG.chocolate,
    categories: ['SNACK'],
    ingredients: [
      { name: 'Proteína en polvo de chocolate', quantity: 30, unit: 'g' },
      { name: 'Yogur griego natural', quantity: 150, unit: 'g' },
      { name: 'Leche', quantity: 50, unit: 'ml' },
    ],
  },
  {
    title: 'Pavo + plátano',
    description: 'Post-gym ultrarápido. Sin preparación, proteína + carbohidrato.',
    instructions: 'Comer 3-4 lonchas de pavo con un plátano mediano.',
    prepTime: 2, cookTime: 0, servings: 1, kcal: 220, imageUrl: IMG.banana,
    categories: ['SNACK'],
    ingredients: [
      { name: 'Pavo en lonchas', quantity: 4, unit: 'lonchas' },
      { name: 'Plátano', quantity: 1, unit: 'unidad' },
    ],
  },
  {
    title: 'Tortitas proteicas',
    description: '~22 g proteína. Sartén 3 min, con mantequilla de cacahuete por encima.',
    instructions: 'Aplastar un plátano maduro. Mezclar con 1 huevo y proteína en polvo. Pequeñas tortitas en sartén antiadherente, 3 min por lado. Servir con mantequilla de cacahuete.',
    prepTime: 5, cookTime: 6, servings: 1, kcal: 220, imageUrl: IMG.pancakes,
    categories: ['SNACK'],
    ingredients: [
      { name: 'Proteína en polvo', quantity: 20, unit: 'g' },
      { name: 'Huevo', quantity: 1, unit: 'unidad' },
      { name: 'Plátano', quantity: 1, unit: 'unidad' },
      { name: 'Mantequilla de cacahuete', quantity: 1, unit: 'cucharada' },
    ],
  },
  {
    title: 'Salmón marinado + guacamole',
    description: 'Merienda saciante. El guacamole es grasa saludable, no te pases de 3 cucharadas.',
    instructions: 'Salmón marinado con guacamole Mercadona. Sin cocinar.',
    prepTime: 3, cookTime: 0, servings: 1, kcal: 300, imageUrl: IMG.salmon,
    categories: ['SNACK'],
    ingredients: [
      { name: 'Salmón marinado', quantity: 100, unit: 'g' },
      { name: 'Guacamole Mercadona', quantity: 3, unit: 'cucharadas' },
    ],
  },
  {
    title: 'Overnight oats de chocolate',
    description: '~25 g proteína. Lo preparas la noche anterior, desayuno o snack listo.',
    instructions: 'La noche anterior: mezclar avena, leche, proteína de chocolate y plátano en un tarro. Tapar y meter en nevera. Por la mañana está listo.',
    prepTime: 5, cookTime: 0, servings: 1, kcal: 280, imageUrl: IMG.porridge,
    categories: ['SNACK', 'DESAYUNO'],
    ingredients: [
      { name: 'Avena', quantity: 50, unit: 'g' },
      { name: 'Leche', quantity: 150, unit: 'ml' },
      { name: 'Proteína en polvo de chocolate', quantity: 25, unit: 'g' },
      { name: 'Plátano', quantity: 1, unit: 'unidad' },
    ],
  },
  {
    title: 'Plátano con mantequilla de cacahuete',
    description: 'El clásico que nunca falla. Saciante, dulce y con proteína.',
    instructions: 'Pelar el plátano. Comer con una cucharada de mantequilla de cacahuete.',
    prepTime: 1, cookTime: 0, servings: 1, kcal: 200, imageUrl: IMG.banana,
    categories: ['SNACK'],
    ingredients: [
      { name: 'Plátano', quantity: 1, unit: 'unidad' },
      { name: 'Mantequilla de cacahuete', quantity: 1, unit: 'cucharada' },
    ],
  },
  {
    title: 'Yogur griego + miel + fruta',
    description: 'Parece postre. Yogur natural sin edulcorar, chorrito de miel y fresas o arándanos.',
    instructions: 'Yogur griego en bol. Chorrito de miel y fresas o arándanos por encima.',
    prepTime: 3, cookTime: 0, servings: 1, kcal: 180, imageUrl: IMG.yogurt,
    categories: ['SNACK'],
    ingredients: [
      { name: 'Yogur griego natural', quantity: 200, unit: 'g' },
      { name: 'Miel', quantity: 1, unit: 'cucharadita' },
      { name: 'Fresas o arándanos', quantity: 80, unit: 'g' },
    ],
  },
  {
    title: 'Mozzarella bolitas + fruta',
    description: 'El dulce de la fruta con la cremosidad del queso. Combinación sorprendente.',
    instructions: 'Servir mozzarella bolitas con fruta fresca a elegir.',
    prepTime: 3, cookTime: 0, servings: 1, kcal: 180, imageUrl: IMG.ensalada,
    categories: ['SNACK'],
    ingredients: [
      { name: 'Mozzarella bolitas', quantity: 80, unit: 'g' },
      { name: 'Fruta fresca', quantity: 100, unit: 'g' },
    ],
  },
  {
    title: 'Porridge frío con chocolate',
    description: 'Sin cocinar, listo en 2 minutos. Avena fría con cacao puro sin azúcar.',
    instructions: 'Mezclar avena con leche fría, cacao puro y plátano troceado. No necesita cocción. Servir frío.',
    prepTime: 2, cookTime: 0, servings: 1, kcal: 260, imageUrl: IMG.porridge,
    categories: ['SNACK'],
    ingredients: [
      { name: 'Avena', quantity: 50, unit: 'g' },
      { name: 'Leche fría', quantity: 150, unit: 'ml' },
      { name: 'Cacao puro sin azúcar', quantity: 1, unit: 'cucharada' },
      { name: 'Plátano', quantity: 1, unit: 'unidad' },
    ],
  },
];
